title: Amazing tiger
description: Amazing tigers of nigeria
template:
  repo: amazing-tiger-template
  name: amazing-tiger
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
